# https://docs.travis-ci.com/user/deployment/pages/
# https://docs.travis-ci.com/user/reference/xenial/
# https://docs.travis-ci.com/user/languages/go/
# https://docs.travis-ci.com/user/customizing-the-build/
dist: xenial
language: go
go:
  - 1.11.x
env:
  - GO111MODULE=on
cache:
  directories:
  - "$HOME/.cache/go-build"
  - "$HOME/gopath/pkg/mod"
before_install:
- mv .travis/private.bak ~/.ssh/id_rsa
- chmod 600 ~/.ssh/id_rsa
# install - install any dependencies required
install:
# - go get github.com/gohugoio/hugo
- wget https://github.com/gohugoio/hugo/releases/download/v0.74.3/hugo_0.74.3_Linux-64bit.deb
- sudo dpkg -i hugo*.deb
before_script:
- mkdir -p public_github 2> /dev/null
- mkdir -p public_gitee 2> /dev/null
# script - run the build script
script:
- hugo --baseURL https://codingriver.github.io/ -d public_github
- hugo --baseURL https://codingriver.gitee.io/ -d public_gitee

deploy:
- script: pwd
- script: ls
- script: mv CNAME-github public_github/CNAME
- script: mv CNAME-gitee public_gitee/CNAME
- provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN" # Set in travis-ci.org dashboard, marked secure
  email: "codingriver@163.com" # Set in travis-ci.org dashboard, marked secure
  name: "codingriver" # Set in travis-ci.org dashboard, marked secure
  repo: "codingriver/codingriver.github.io"
  target_branch: master
  verbose: true
  keep-history: false
  local-dir: public_github
  on:
    branch: master
- provider: script
  skip-cleanup: true
  script: bash .travis/deploy_to_gitee.sh
  on:
    branch: master
addons:
  ssh_known_hosts:
  - github.com
  - gitee.com