name: sync gitee
on:
# 如果需要PR触发把push前的#去掉
# push:
  schedule:
    # 每天北京
    - cron:  '*/5 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Single repo mirror
      uses: Yikun/hub-mirror-action@master
      with:
        src: gitee/codingriver
        dst: github/codingriver
        dst_key: ${{ secrets.ACTIONS_SYNC_GITEE }}
        dst_token: ${{ secrets.SYNC_TOKEN }}
        white_list: "hugo-project"